# --- Geometry & Positioning ---
anchor = left center
margin = 50
width = 30
height = 400

# --- Colors (Purple Theme) ---
# Bar and Border: Purple
bar_color = B392F0BF
border_color = B392F0BF

# Background: Transparent (00 at the end)
background_color = 00000000

# --- Overflow (Red-Purple Theme) ---
overflow_bar_color = AC3232FF
overflow_background_color = 00000000
overflow_border_color = AC3232FF

# --- Behavior ---
timeout = 1000
max = 100

orientation = vertical
